name: Deploy to S3

on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy to S3
        run: |
          # Copy index.html with no-cache headers
          aws s3 cp ./dist/index.html s3://${{ secrets.S3_BUCKET_NAME }}/ \
            --content-type "text/html" \
            --cache-control "no-cache, no-store, must-revalidate"
          
          # Sync other files (excluding index.html and images)
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}/ \
            --exclude index.html \
            --exclude "images/*" \
            --delete